# Generated by Django 3.2.14 on 2024-02-23 03:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='都道府県', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TVStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='放送局', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='No Title', max_length=255)),
                ('detail', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('tv_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.tvstation')),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('channel', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='api.location')),
                ('tv_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='api.tvstation')),
            ],
        ),
    ]
