# Generated by Django 3.2.14 on 2024-04-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='detail',
        ),
    ]
